
DIRS += $(ADAPTATION)/gnrc-netface
DIRS += $(ADAPTATION)/gnrc-udp
DIRS += $(ADAPTATION)/security
DIRS += $(ADAPTATION)/util

USEMODULE += gnrc_netdev_default
USEMODULE += auto_init_gnrc_netif
USEMODULE += gnrc_ipv6
USEMODULE += gnrc_udp

USEMODULE += shell
USEMODULE += shell_commands
USEMODULE += ps
USEMODULE += xtimer


USEMODULE += ndn-adaptation-gnrc-netface
USEMODULE += ndn-adaptation-gnrc-udp
USEMODULE += ndn-adaptation-util
USEMODULE += ndn-adaptation-security