
DIRS += $(ADAPTATION)/gnrc-netface
DIRS += $(ADAPTATION)/security
DIRS += $(ADAPTATION)/util

USEMODULE += ndn-adaptation-gnrc-netface
USEMODULE += ndn-adaptation-util
USEMODULE += ndn-adaptation-security

USEMODULE += gnrc_netdev_default
USEMODULE += auto_init_gnrc_netif
USEMODULE += shell
USEMODULE += shell_commands
USEMODULE += ps
USEMODULE += xtimer
